from pathlib import Path


DEFAULT_CONFIG = """# Generated by blender_gs_colmap_exporter 1.4.0
schema_version: "1.0"
device: "cuda:0"
seed: 42
scene:
  normalize: true
  unit: meter
data:
  image_scale: 1.0
  validation_scale: 1.0
  cache_size: 8
  num_workers: 2
  pin_memory: true
  color_space: from_metadata
  depth_type: from_metadata
  normal_space: from_metadata
model:
  sh_degree_start: 0
  sh_degree_max: 3
  anchor_mode: hard
  normal_offset_max_meters: 0.003
  max_gaussians: 4000000
  initial_normal_scale_ratio: 0.05
training:
  mixed_precision: true
  eval_every: 500
  checkpoint_every: 1000
  preview_every: 1000
  log_every: 10
  fail_on_missing_optional_supervision: false
  require_triangle_images: true
stages:
  stage_1:
    name: appearance_initialization
    steps: 3000
    train_appearance: true
    train_geometry: false
    densification: false
  stage_2:
    name: surface_coverage
    steps: 5000
    train_appearance: true
    train_geometry: true
    densification: false
  stage_3:
    name: error_driven_densification
    steps: 12000
    train_appearance: true
    train_geometry: true
    densification: true
  stage_4:
    name: appearance_refinement
    steps: 5000
    train_appearance: true
    train_geometry: false
    densification: false
loss:
  rgb_l1: 0.8
  dssim: 0.2
  depth: 0.10
  normal: 0.05
  surface_anchor: 1.0
  normal_alignment: 0.05
  thin_scale: 0.05
  opacity_regularization: 0.001
optimizer:
  sh_dc_lr: 0.0025
  sh_rest_lr: 0.000125
  opacity_lr: 0.05
  tangent_scale_lr: 0.005
  normal_scale_lr: 0.001
  rotation_lr: 0.001
  barycentric_lr: 0.0001
  normal_offset_lr: 0.00001
  lr_final_factor: 0.1
densification:
  start_step: 8000
  stop_step: 19000
  interval: 100
  max_gaussians: 4000000
  min_opacity: 0.005
  gradient_threshold: 0.0002
  split_scale_threshold: 0.02
  max_scale_threshold: 1.0
  max_screen_radius: 4096.0
  max_invisible_steps: 1000
  min_error_for_prune: 0.00000001
  min_error_prune_after: 2000
  inherit_mesh_anchor: true
  allow_adjacent_triangle_transfer: false
"""


def write_training_config(root):
    path = Path(root) / "config" / "training_config.yaml"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(DEFAULT_CONFIG, encoding="utf-8", newline="\n")
    return path

